version: '3.1'

services:

  api:
    image: nginx
    restart: always
    environment:
      VIRTUAL_HOST: monitor.saniaky.com

  db:
    image: mysql:5.7
    container_name: monitor_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports: ['3333:3306']
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: monitor
      # MYSQL_USER
      # MYSQL_PASSWORD
